# Generated by Django 3.2.4 on 2021-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saka_Social_Network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='date_envoye',
        ),
        migrations.AddField(
            model_name='discussion',
            name='liste_message',
            field=models.IntegerField(null=True),
        ),
    ]
