# Generated by Django 3.2.4 on 2021-07-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saka_Social_Network', '0002_auto_20210719_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_amis', models.IntegerField(null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saka_Social_Network.utilisateur')),
            ],
        ),
    ]
