# Generated by Django 3.2.4 on 2021-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0003_ami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contenus',
            field=models.TextField(max_length=500),
        ),
    ]
