# Generated by Django 3.2.4 on 2021-07-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0004_alter_message_contenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sakanet.discussion'),
        ),
    ]
