# Generated by Django 3.2.5 on 2021-07-31 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sakanet', '0006_alter_message_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='photo',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
