# Generated by Django 3.2.5 on 2021-07-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0007_auto_20210731_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
    ]
