# Generated by Django 3.2.5 on 2021-08-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0007_auto_20210815_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
