# Generated by Django 3.2.5 on 2021-08-15 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sakanet', '0010_alter_message_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contenus',
            field=models.TextField(max_length=150),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
                ('contenus_pub', models.TextField(max_length=150)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
