# Generated by Django 3.2.5 on 2021-09-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0016_auto_20210906_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_sender',
            new_name='sender',
        ),
    ]
