# Generated by Django 3.2.5 on 2021-09-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakanet', '0017_auto_20210906_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contenus',
            new_name='message',
        ),
    ]
